language: bash

sudo: required

services:
  - docker

before_script:
    - curl -s -L "https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz"      | tar zxv 
        && ln -s bats-0.4.0 bats

script: bats/bin/bats test
