language: bash

#before_script:
#    - curl -s -L "https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz"      | tar zxv -C /tmp
#        && bash /tmp/bats-0.4.0/install.sh /usr/local/ \
#        && rm -fr /tmp/bats-0.4.0

script: bats test
